version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every monday
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "Asia/Tokyo"
    groups:
      angular:
        patterns:
          - "*"
        update-types:
          - major
          - minor
          - patch
