runner:
  statix:
    cmd: statix check -o errfmt | cat
    errorformat:
      - "%f>%l:%c:%t:%n:%m"
    level: warning

  typos:
    cmd: typos --exclude CHANGELOG.md
    format: typos

  actionlint:
    cmd: SHELLCHECK_OPTS='-e SC2086' actionlint -oneline
    errorformat:
      - "%f:%l:%c: %m"
    level: warning
