keys:
  - &users:
    - &sumi_mother age1w4dld6acqnhctzq32nhnajw0ewgkq7295k3ue3cgg0pwpt0re3asg4ajs3
    - &sumi_soleus age1kqv66hq8wtmfdqek5sa7ydklwxkrdn3cn4ptvwrl9f3eqx04s5rq7nrsk3
    - &sumi_stacia age1znnqnxjkr0x70r5ys0n2k34ym5a3spn69yuveqa76wh0ng65catspphysl
    - &sumi_zephyrus age1rv448rkxyuf69u4enm2mmjl5r4cshxtq3xepjjzru3awa2k83puqul7scg
creation_rules:
  - path_regex: sops/secrets/ssh/desktops$
    key_groups:
      - age:
          - *sumi_mother
          - *sumi_zephyrus
  - path_regex: sops/secrets/ssh/servers$
    key_groups:
      - age:
          - *sumi_mother
          - *sumi_zephyrus
  - path_regex: sops/secrets/ssh/univ$
    key_groups:
      - age:
          - *sumi_mother
          - *sumi_soleus
          - *sumi_stacia
          - *sumi_zephyrus
  - path_regex: sops/secrets/wezterm/[^/]+\.lua$
    key_groups:
      - age:
          - *sumi_mother
          - *sumi_soleus
          - *sumi_stacia
          - *sumi_zephyrus
