keys:
  - &users:
    - &sumi_mother age1w4dld6acqnhctzq32nhnajw0ewgkq7295k3ue3cgg0pwpt0re3asg4ajs3
    - &sumi_stacia age1znnqnxjkr0x70r5ys0n2k34ym5a3spn69yuveqa76wh0ng65catspphysl
    - &sumi_zephyrus age1rv448rkxyuf69u4enm2mmjl5r4cshxtq3xepjjzru3awa2k83puqul7scg
  - &desktops:
    - &mother: age1dx0hn7ug2nfd9sxw0q3hvegh8llqt0084x7gzk20s20lptrujs6sv48akw
    - &stacia age12994fjtztfkz06rtg0w6gxrzne3z0y223zumu293jtdsfukukussq233na
    - &zephyrus: age1lc2dnrqr84rat2aqmm9g78mssuxm40vsswr7lnaz59n97qjgg9csx2wekj
creation_rules:
  - path_regex: sops/secrets/ssh/desktops
    key_groups:
      - age:
          - *sumi_mother
          - *sumi_zephyrus
  - path_regex: sops/secrets/ssh/servers
    key_groups:
      - age:
          - *sumi_mother
          - *sumi_zephyrus
  - path_regex: sops/secrets/ssh/univ
    key_groups:
      - age:
          - *sumi_mother
          - *sumi_stacia
          - *sumi_zephyrus
  - path_regex: sops/secrets/wezterm/[^/]+\.lua$
    key_groups:
      - age:
          - *sumi_mother
          - *sumi_stacia
          - *sumi_zephyrus
