name: auto approve
on:
  workflow_run:
    workflows:
      - "build check"
      - "reviewdog"
    types:
      - completed

permissions: write-all
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: contains(fromJSON('["misumisumi"]'), github.actor)
    env:
      GITHUB_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
    steps:
      # From https://github.com/orgs/community/discussions/25220#discussioncomment-8697399
      - uses: actions/github-script@v7
        id: pr
        with:
          script: |
            const response = await github.rest.search.issuesAndPullRequests({
              q: 'repo:${{ github.repository }} is:pr sha:${{ github.event.workflow_run.head_sha }}',
              per_page: 1,
            })
            const items = response.data.items
            if (items.length < 1) {
              console.error('No PRs found')
              return
            }
            const pullRequestNumber = items[0].number
            console.info("Pull request number is", pullRequestNumber)
            return pullRequestNumber

      - name: Auto approve
        env:
          PR_NUM: ${{ steps.pr.outputs.result }}
        run: |
          gh pr review --approve "${PR_NUM}"
