name: Auto approve
on:
  workflow_run:
    workflows: "*"
    types:
      - completed

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: contains(fromJSON('["misumisumi", "app/operate-pr-for-flakes"]'), github.actor)
    outputs:
      pr-number: ${{ steps.pr.outputs.result }}
    steps:
      # From https://github.com/orgs/community/discussions/25220#discussioncomment-8697399
      - name: Find associated pull request
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.search.issuesAndPullRequests({
              q: 'repo:${{ github.repository }} is:pr sha:${{ github.event.workflow_run.head_sha }}',
              per_page: 1,
            })
            const items = response.data.items
            if (items.length < 1) {
              console.error('No PRs found')
              return
            }
            const pullRequestNumber = items[0].number
            console.info("Pull request number is", pullRequestNumber)
            return pullRequestNumber

      - name: Check workflow status
        id: check-workflow-status
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          status_check=$(gh pr view ${{ steps.pr.outputs.result }} --json statusCheckRollup)
          completed=$(echo $status_check | jq -r '.statusCheckRollup | [.[] | select(.status=="COMPLETED")]')
          if [ $(cat $completed | jq -r '. | length' ) -eq $(cat $status_check | jq -r '.statusCheckRollup | length') ]; then
            if [ $(cat $completed | jq '[.[].conclusion] | all(.=="SUCCESS" or "NEUTRAL")') == true ]; then
              gh pr review --approve ${{ steps.pr.outputs.result }} --repo ${{ github.repository }}
            end
          end
