name: Auto approve
on:
  workflow_run:
    workflows: [Build check]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: >-
      github.event.workflow_run.conclusion == 'success'
    outputs:
      pr-number: ${{ steps.pr-number.outputs.pr-number }}
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build-check.yml
          workflow_conclusion: success
          name: pr-number
          path: artifacts

      - name: Set PR number
        id: pr-number
        run: |
          echo pr-number=$(cat ./artifacts/pr-number.txt) >> $GITHUB_OUTPUT

      - name: Check PR Author
        id: pr-author
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          echo pr-author=$(gh pr view ${{ steps.pr-number.outputs.pr-number }} --json author --jq .author.login) >> $GITHUB_OUTPUT

      - name: PR review and merge
        id: pr-approve
        if: >-
          steps.pr-author.outputs.pr-author == "misumisumi" ||
          steps.pr-author.outputs.pr-author == "app/operate-pr-for-flakes"
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh pr review --approve ${{ needs.check-pr.outputs.pr-number.outputs.pr-number }}
          gh pr merge --merge --auto ${{ needs.check-pr.outputs.pr-number.outputs.pr-number }}

      - name: Not Approve
        if: steps.pr-approve.conclusion != 'success'
        run: |
          exit 1

  on-failure:
    runs-on: ubuntu-latest
    needs: on-success
    if: >-
      needs.on-success.result != 'success'
    steps:
      - name: Error handling
        run: |
          echo "Not approve"
          exit 1
