name: Build check
on:
  pull_request:
    paths:
      - "**.nix"
      - "flake.lock"

permissions: read-all
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          swap-size-mb: 1024
          build-mount-path: "/nix/store"
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: cachix/cachix-action@v12
        with:
          name: misumisumi
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true

      - name: Build Check
        id: build-check
        run: nix run "github:nix-community/home-manager" -- build -j 4 --flake ".#test"

      - name: Create package list
        env:
          PR_NUM: ${{ github.event.number }}
        run: |
          nix path-info -r ./result | cut -d'-' -f2- | sort | sed -e "s/-[a-z]\+$//g" | uniq > current-nixpkgs.list

      - uses: actions/upload-artifact@v4
        if: ${{ github.actor == 'app/update-flake' }}
        with:
          name: current-nixpkgs
          path: current-nixpkgs.list
          overwrite: true
