name: update repository
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 19 * * 5" # runs weekly on Saturday at 04:00 (JST)

permissions: read-all

jobs:
  update-repo:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'misumisumi'
    steps:
      - uses: actions/checkout@v4

      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: DeterminateSystems/update-flake-lock@v21
        id: update
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-msg: "chore(flake.lock): auto update flake.lock"
          pr-title: "chore(flake.lock): auto update flake.lock" # Title of PR to be created
          pr-labels: | # Labels to be set on the PR
            dependencies
            automated
