name: Update repository
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 18 * * 5" # runs weekly on Saturday at 03:00 (JST)

jobs:
  update-repo:
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.update.outputs.pull-request-number }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub Apps token
        id: generate
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update flake lock
        id: update
        uses: DeterminateSystems/update-flake-lock@v21
        with:
          token: ${{ steps.generate.outputs.token }}
          commit-msg: "Update flake and package version"
          pr-title: "Update repository" # Title of PR to be created
          pr-labels: | # Labels to be set on the PR
            dependencies
            automated
